# Generated by Django 4.1.7 on 2023-04-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_feeding_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='feeding date'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('M', 'Milk/Formula'), ('BF', 'Baby Food/Puree'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], default='S', max_length=2, verbose_name='meal type'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='time',
            field=models.TimeField(verbose_name='feeding time'),
        ),
    ]
