# Generated by Django 4.1.7 on 2023-04-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_event_delete_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(choices=[('A', 'Activity'), ('D', 'Diaper'), ('F', 'Feeding'), ('M', 'Medicine'), ('N', 'Nap'), ('S', 'Sick')], default='A', max_length=1, verbose_name='event type'),
        ),
    ]
