# Generated by Django 4.1.7 on 2023-05-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
